[package]
name = "grbl-sender"
version = "0.1.0"
authors = ["Elijah Insua <tmpvar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "3.3.0"
clap = "2.33.0"
colored = "1.8.0"
